CREATE TABLE TESTCASE1(
    numNo NUMBER PRIMARY KEY,
    name VARCHAR2(10) NOT NULL,
    age NUMBER CONSTRAINT checkAge CHECK(age >= 1 AND age <= 120),
    sex CHAR CONSTRAINT checkSex CHECK(sex IN('W', 'M'))
);

INSERT INTO TESTCASE1 VALUES( 1, 'KING', 25, 'W');
INSERT INTO TESTCASE1 VALUES( 2, 'KONG', 35, 'W');
INSERT INTO TESTCASE1 VALUES( 3, 'KOOG', 45, 'M');
INSERT INTO TESTCASE1 VALUES( 4, 'QOO', 55, 'W');
INSERT INTO TESTCASE1 VALUES( 5, 'JOO', 5, 'M');

SELECT * FROM TESTCASE1;

CREATE TABLE TESTCASE2(
    no NUMBER,
    CONSTRAINT newNo
    FOREIGN KEY(NO)
    REFERENCES TESTCASE1(NUMNO)
    );
    
INSERT INTO TESTCASE2 VALUES(2);
INSERT INTO TESTCASE2 VALUES(2);
INSERT INTO TESTCASE2 VALUES(2);

SELECT no FROM TESTCASE2;


DROP TABLE TESTCASE3;
CREATE TABLE TESTCASE3 (
    no NUMBER,
    FOREIGN KEY (NO)
    REFERENCES TESTCASE1(NUMNO)
    ON DELETE CASCADE
   -- ON DELETE NOT NULL 
   -- 널값이 들어가지 않음
    );

ALTER TABLE TESTCASE1 ADD ( phone number);
ALTER TABLE TESTCASE1 MODIFY (phone VARCHAR2(20));
-- 기존의 데이터가 있다면 바꿀수 없다.
ALTER TABLE TESTCASE1 DROP COLUMN phone;
desc testcase1;

ALTER TABLE TESTCASE1 SET UNUSED (phone);
ALTER TABLE TESTCASE1 DROP UNUSED COLUMNS ;

ALTER TABLE TESTCASE1 RENAME COLUMN SEX TO Gender;    
    
desc TESTCASE1;

ALTER TABLE TESTCASE1 RENAME TO INFO;

DESC INFO;

ALTER TABLE INFO RENAME TO TESTCASE1;

ALTER TABLE TESTCASE1 ADD CONSTRAINT UNAME UNIQUE(NAME);
ALTER TABLE TESTCASE1 MODIFY AGE NOT NULL ;
ALTER TABLE TESTCASE1 MODIFY AGE NULL;
ALTER TABLE TESTCASE1 ADD (PHONE NUMBER );

ALTER TABLE TESTCASE1 MODIFY PHONE UNIQUE;

DESC TESTCASE1;

CREATE TABLE INFO(
    DATA1 NUMBER,
    DATA2 VARCHAR2(10),
    DATA3 VARCHAR2(10)
    );
    
ALTER TABLE INFO ADD CONSTRAINT PK PRIMARY KEY (DATA1);
ALTER TABLE INFO DROP CONSTRAINT PK;
-- 컬럼데이터는 보존되고 제약조건만 제거된다.

ALTER TABLE INFO MODIFY (DATA2 NUMBER);

DESC INFO;
DESC TESTCASE1; 

ALTER TABLE INFO ADD CONSTRAINT FK FOREIGN KEY (DATA2)
REFERENCES TESTCASE1 (NUMNO) ;

DESC INFO;






CREATE TABLE INFO2 (
    DATA1 NUMBER,
    DATA2 DATE DEFAULT SYSDATE,
    DATA3 VARCHAR2(10)
    );

ALTER TABLE INFO2 ADD PRIMARY KEY(DATA3);
ALTER TABLE INFO2 ADD FOREIGN KEY(DATA1)
REFERENCES TESTCASE1 (NUMNO);

ALTER TABLE INFO2 RENAME COLUMN DATA2 TO TODAY;

INSERT INTO INFO2 (DATA1, DATA3) VALUES (1, 'AA');
INSERT INTO INFO2 (DATA1, DATA3) VALUES (2, 'BA');
INSERT INTO INFO2 (DATA1, DATA3) VALUES (3, 'CA');
SELECT * FROM INFO2;

ALTER TABLE INFO2 SET UNUSED (TODAY);

ALTER TABLE INFO2 DROP UNUSED COLUMNS ;

DESC INFO2;

TRUNCATE TABLE INFO2;
-- 테이블의 구조는 유지하면서 데이터만 삭제한다.

SELECT * FROM INFO2;

DROP TABLE INFO2;
-- 완전 테이블 삭제

CREATE TABLE INFO2 (
    DATA1 NUMBER NOT NULL,
    DATA2 DATE DEFAULT SYSDATE,
    DATA3 VARCHAR(10),
    CONSTRAINT PK PRIMARY KEY (DATA3)
    );


ALTER TABLE INFO2 ADD FOREIGN KEY (DATA1)
REFERENCES TESTCASE1 (NUMNO);

ALTER TABLE INFO2 RENAME COLUMN DATA2 TO THISDAY;
ALTER TABLE INFO2 MODIFY THISDAY UNIQUE;
ALTER TABLE INFO2 SET UNUSED (THISDAY);

ALTER TABLE INFO2 DROP UNUSED COLUMNS;

DESC INFO2;

TRUNCATE TABLE INFO2;
DESC INFO2;

DROP TABLE INFO2;

CREATE TABLE INFO2 (
    DATA1 CLOB,
    DATA2 NUMBER,
    DATA3 VARCHAR2(10)
    );
    
INSERT INTO INFO2 VALUES('GKGKGKLDKA;DKWOPDKASLMXZ.CMZ.,XMC.ZXMDOWEQDASMLC.,ZMDKWQMD,MC,Z.XOWQFKS;DLL'
, 25, 'HI');

SELECT DATA1, DATA2, DATA3 FROM INFO2;



