--1. 2014년 1월 2일 내원환자 전체 정보조회
--   환자번호, 환자이름, 생년월일, 성별, 진료의사명, 진료과명
-- 스칼라 서브쿼리로 표현

SELECT P.PAT_CODE
, P.PAT_NAME 
, P.PAT_BIRTH
, P.PAT_GENDER
, (SELECT D. DOC_NAME FROM DOCTOR D 
    WHERE T.DOC_CODE = D.DOC_CODE) AS "진료의사명"
, (SELECT DE. DEP_NAME FROM DEPARTMENT DE, DOCTOR D
    WHERE DE.DEP_CODE = D.DEP_CODE
    AND T.DOC_CODE = D.DOC_CODE ) "진료과명"
FROM PATIENT P, TREAT T
WHERE P.PAT_CODE = T.PAT_CODE
AND T.TRT_YEAR = '2014' AND T.TRT_DATE = '0102'
ORDER BY PAT_CODE;


--2.2014년 1월 2일 내원환자 중 부서테이블을 WHERE 절 SubQuery를 
--사용하여 조회
--   환자번호, 환자이름, 생년월일, 성별, 진료의사명, 진료과명

-- 단 외과계열 환자만조회('02xx')
-- where절 subquery

SELECT DISTINCT P.PAT_CODE
, P.PAT_NAME
, P.PAT_BIRTH
, P.PAT_GENDER
, D.DOC_NAME
, DE.DEP_NAME
FROM PATIENT P , TREAT T, DOCTOR D, DEPARTMENT DE
WHERE T.TRT_YEAR = '2014' AND T.TRT_DATE = '0102'
AND '02' = SUBSTR(DE.DEP_CODE,1,2)
AND P.PAT_CODE = T.PAT_CODE
AND D.DOC_NAME IN(SELECT DOC_NAME FROM DOCTOR D 
    WHERE D.DOC_CODE = T.DOC_CODE )
AND DE.DEP_NAME IN(SELECT DEP_NAME FROM DEPARTMENT DE, DOCTOR D
    WHERE DE.DEP_CODE = D.DEP_CODE
    AND D.DOC_CODE = T.DOC_CODE)
ORDER BY P.PAT_CODE;


