--1. 2012년 1월 3일 내원환자 중 
-- 정형외과(코드:05xx)와 성형외과(코드:08xx)와 이비인후과(코드:13xx)
-- 환자조회
SELECT DISTINCT P.PAT_CODE, P.PAT_NAME
FROM PATIENT P, DEPARTMENT DE, TREAT T, DOCTOR D
WHERE P.PAT_CODE = T.PAT_CODE
AND D.DEP_CODE = DE.DEP_CODE
AND D.DOC_CODE = T.DOC_CODE
AND (TRT_DATE = '0103' AND TRT_YEAR = '2012')
AND('05' = SUBSTR(DE.DEP_CODE,1,2)
OR '08' = SUBSTR(DE.DEP_CODE,1,2)
OR '13' = SUBSTR(DE.DEP_CODE,1,2))
ORDER BY P.PAT_CODE;


--2. 2012년 1월 3일 내원환자 중 내원 진료시간이 09:00 ~ 12:00 이고
-- 진료과가 정형외과(코드:05xx)와 성형외과(코드:08xx)와 이비인후과(코드:13xx)
-- 가 아닌 환자조회
SELECT TRT_TIME FROM TREAT;

SELECT DISTINCT P.PAT_CODE, P.PAT_NAME
FROM PATIENT P, DEPARTMENT DE, TREAT T ,DOCTOR D 
WHERE P.PAT_CODE = T.PAT_CODE
AND D.DEP_CODE = DE.DEP_CODE
AND D.DOC_CODE = T.DOC_CODE
AND (TRT_DATE = '0103' AND TRT_YEAR = '2012')
AND TRT_TIME BETWEEN 0900 AND 1200 
AND ('05' != SUBSTR(D.DEP_CODE,1,2)
AND '08' != SUBSTR(D.DEP_CODE,1,2)
AND '13' != SUBSTR(D.DEP_CODE,1,2))
ORDER BY P.PAT_CODE;


--3. 2014년 1월 1일 내원환자 중 5명만 출력
-- (진료시간순서 상 마지막 진료환자 5명)

SELECT PAT_NAME
FROM PATIENT P, DEPARTMENT D, TREAT T
ORDER BY PAT_NAME LIMIT 5;

